"""Oversight (Art. 14, GDPR Art. 22) and disclosure (Art. 50) events on the action chain.

Each guarantee has a control that fails: an oversight with no actor, a reference to an action that
does not exist, a reference rewritten on disk, a disclosure with nothing shown, and a compliance
report read over a rewritten ledger.
"""
import json

import pytest

from inspeximus import Inspeximus, new_receipt_keypair
from inspeximus.actions import ActionLedger, verify_file, OVERSIGHT_EVENTS
from inspeximus.compliance import compliance_report

pytest.importorskip("cryptography")


def _led(tmp_path):
    sk, pk = new_receipt_keypair()
    m = Inspeximus(str(tmp_path / "mem.json"), receipts=True, receipt_key=sk)
    m.remember("the refund limit is 50", key="limit")
    return m, ActionLedger(m, actor="agent"), pk


def test_an_oversight_event_names_its_actor_and_resolves_to_the_action_it_concerns(tmp_path):
    m, led, pk = _led(tmp_path)
    with pytest.raises(RuntimeError):
        with led.action("tool:transfer", inputs={"amt": 9}):
            raise RuntimeError("limit")
    e = led.oversight("override", "ops-lead", reason="manual", refers_to=0, decision={"amt": 5})
    assert e["kind"] == "oversight" and e["actor"] == "ops-lead"
    assert e["refers_to"] == {"seq": 0, "hash": led.entries()[0]["hash"]}
    assert "decision" not in e and e["decision_sha256"]
    assert led.verify(expected_pubkey=pk) == (True, [])
    rep = led.oversight_report()
    assert rep["by_event"] == {"override": 1} and rep["by_actor"] == {"ops-lead": 1}
    assert rep["error_actions_without_oversight"] == []


def test_every_oversight_event_kind_is_accepted_and_nothing_else(tmp_path):
    m, led, pk = _led(tmp_path)
    for ev in OVERSIGHT_EVENTS:
        led.oversight(ev, "reviewer")
    with pytest.raises(ValueError):
        led.oversight("bless", "reviewer")
    assert led.oversight_report()["oversight_events"] == len(OVERSIGHT_EVENTS)


def test_an_oversight_event_without_an_actor_is_refused_and_a_bad_reference_is_refused(tmp_path):
    m, led, pk = _led(tmp_path)
    with pytest.raises(ValueError):
        led.oversight("approve", "")
    with pytest.raises(ValueError):
        led.oversight("approve", "x", refers_to=7)
    with pytest.raises(ValueError):
        led.oversight("approve", "x", refers_to="ff" * 32)
    assert len(led) == 0


def test_a_reference_rewritten_on_disk_fails_verification(tmp_path):
    m, led, pk = _led(tmp_path)
    led.record("tool:a")
    led.record("tool:b")
    led.oversight("review", "dpo", refers_to=1)
    assert verify_file(led.path)[0]
    data = json.loads(led.path.read_text(encoding="utf-8"))
    data[2]["refers_to"]["seq"] = 0
    led.path.write_text(json.dumps(data), encoding="utf-8")
    ok, problems = verify_file(led.path)
    assert not ok and any("refers_to does not resolve" in p for p in problems)
    # CONTROL: an actor stripped on disk is reported by name, not only as a hash mismatch
    data = json.loads(led.path.read_text(encoding="utf-8"))
    data[2]["refers_to"]["seq"] = 1
    data[2]["actor"] = None
    led.path.write_text(json.dumps(data), encoding="utf-8")
    ok, problems = verify_file(led.path)
    assert not ok and any("no actor" in p for p in problems)


def test_an_error_action_with_no_oversight_after_it_is_listed(tmp_path):
    m, led, pk = _led(tmp_path)
    led.record("tool:a", status="error", error="boom")
    led.record("tool:b", status="error", error="boom")
    led.oversight("review", "dpo", refers_to=1)
    assert led.oversight_report()["error_actions_without_oversight"] == [0]


def test_a_disclosure_records_session_channel_kind_and_length_but_not_the_text(tmp_path):
    m, led, pk = _led(tmp_path)
    e = led.disclosure("s1", "You are chatting with an AI assistant.", channel="web")
    assert e["kind"] == "disclosure" and e["session"] == "s1" and e["disclosure_kind"] == "interaction"
    assert e["shown_chars"] == 38 and "shown" not in e and e["shown_sha256"]
    with pytest.raises(ValueError):
        led.disclosure("s1", "")
    with pytest.raises(ValueError):
        led.disclosure("s1", "x", kind="banner")
    assert led.oversight_report()["sessions_disclosed"] == {"s1": ["interaction"]}
    led2 = ActionLedger(m, keep_content=True)
    e2 = led2.disclosure("s2", "Generated by an AI system.", kind="generated_content")
    assert e2["shown"] == "Generated by an AI system."


def test_the_compliance_report_reads_the_ledger_and_treats_a_rewritten_one_as_no_evidence(tmp_path):
    m, led, pk = _led(tmp_path)
    led.disclosure("s1", "You are chatting with an AI assistant.")
    led.record("tool:a")
    led.oversight("approve", "dpo", refers_to=1)
    r = compliance_report(m)
    by_art = {c["article"]: c for c in r["controls"]}
    assert by_art["Art. 14"]["status"] == "evidence" and by_art["Art. 14"]["live_count"] == 1
    assert by_art["Art. 22"]["status"] == "evidence"
    assert by_art["Art. 50"]["status"] == "evidence" and by_art["Art. 50"]["live_count"] == 1
    assert by_art["Art. 12 (actions)"]["live_count"] == 1
    assert len(r["controls"]) == 11          # the README publishes this count
    assert r["action_ledger"]["ledger_verified"] is True
    # CONTROL: rewrite the ledger; the report must not count it as evidence
    data = json.loads(led.path.read_text(encoding="utf-8"))
    data[1]["action"] = "tool:z"
    led.path.write_text(json.dumps(data), encoding="utf-8")
    r2 = compliance_report(m)
    by_art2 = {c["article"]: c for c in r2["controls"]}
    assert r2["action_ledger"]["ledger_verified"] is False
    assert by_art2["Art. 14"]["status"] == "available" and by_art2["Art. 14"]["live_count"] == 0


def test_a_store_with_no_ledger_reports_the_new_controls_as_available(tmp_path):
    m = Inspeximus(str(tmp_path / "plain.json"), receipts=True)
    m.remember("x", key="k")
    r = compliance_report(m)
    by_art = {c["article"]: c for c in r["controls"]}
    assert by_art["Art. 14"]["status"] == "available"
    assert r["action_ledger"]["ledger_present"] is False
