"""The plan's obligation table is generated from inspeximus.coverage and must match it.

The hand-written table went stale for four duties within two days (2026-09-15 to 2026-09-17), so the
block between the markers is regenerated by tools/gen_coverage_table.py and this fails when the plan
and the code disagree, the way docs/CORE_MAP.md is guarded.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_docs_plan_coverage_block_matches_the_code():
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "gen_coverage_table.py"), "--check"],
                       capture_output=True, text=True, encoding="utf-8", cwd=ROOT)
    assert r.returncode == 0, r.stdout + r.stderr


def test_the_coverage_page_carries_the_generated_block():
    """docs/COVERAGE.md holds the generated matrix between its markers and nothing hand-edited inside them."""
    text = open(os.path.join(ROOT, "docs", "COVERAGE.md"), encoding="utf-8").read()
    assert "coverage:begin" in text and "coverage:end" in text
    assert "in-scope duties covered by the library" in text
