"""The plan's obligation table is generated from inspeximus.coverage and must match it.

The hand-written table went stale for four duties within two days (2026-09-15 to 2026-09-17), so the
block between the markers is regenerated by tools/gen_coverage_table.py and this fails when the plan
and the code disagree, the way docs/CORE_MAP.md is guarded.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_docs_plan_coverage_block_matches_the_code():
    r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "gen_coverage_table.py"), "--check"],
                       capture_output=True, text=True, encoding="utf-8", cwd=ROOT)
    assert r.returncode == 0, r.stdout + r.stderr


def test_the_plan_names_the_procedure_and_the_order():
    text = open(os.path.join(ROOT, "docs", "EVIDENCE_PLATFORM_PLAN.md"), encoding="utf-8").read()
    assert "## 0. The whole Act, step by step" in text
    for step in ("2.42.0", "2.43.0", "2.44.0", "2.45.0", "2.46.0"):
        assert step in text
    assert "coverage:begin" in text and "coverage:end" in text
