"""Annex IV technical documentation and Art. 13 instructions for use, generated from the evidence.

EU AI Act Art. 11 requires technical documentation for a high-risk system, and Annex IV lists its
contents. Most of Annex IV is the provider's own account: intended purpose, design choices, the risk
management system, the declaration of conformity. A memory and action ledger cannot write those.
What it can write is the evidence the account rests on: which logs exist, what they cover, how an
auditor verifies them, what the store holds, what oversight happened, what was erased. This module
fills those parts from the live store and ledger and marks every other field as operator input, so
the output is a skeleton with the evidence in place and the gaps named, never a finished document.

Art. 13(3)(f) asks the instructions for use to explain how to collect, store and interpret the logs.
`instructions_for_use()` is that section for this store: the file layout, the entry schema, the
verifier commands and the retention behaviour, written from the code that runs, not from memory.

    from inspeximus.technical_documentation import annex_iv, instructions_for_use, render_markdown

    doc = annex_iv(store, ledger=led, operator={"system_name": "Support agent", "provider": "Acme GmbH"})
    open("annex_iv.md", "w").write(render_markdown(doc))

Evidence, not a conformity assessment. Article references are to Regulation (EU) 2024/1689 as
amended by Regulation (EU) 2026/1744; check them against the Official Journal before relying on them.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from typing import Any

from .core import __version__

__all__ = ["annex_iv", "instructions_for_use", "registration_export", "render_markdown", "OPERATOR_FIELDS",
           "REGISTRATION_FIELDS"]

OPERATOR_INPUT = "OPERATOR INPUT REQUIRED"

#: The Annex IV fields the ledger cannot fill. Each maps to the Annex IV item it belongs to.
OPERATOR_FIELDS = {
    "system_name": "1(a)", "intended_purpose": "1(a)", "provider": "1(a)", "system_version": "1(a)",
    "interaction_with_other_systems": "1(b)", "software_and_firmware_versions": "1(c)",
    "forms_placed_on_market": "1(d)", "hardware_description": "1(e)",
    "photographs_or_illustrations": "1(f)", "user_interface": "1(g)",
    "design_methods_and_third_party_tools": "2(a)", "design_specifications_and_logic": "2(b)",
    "system_architecture": "2(c)", "training_data_and_datasheets": "2(d)",
    "human_oversight_measures": "2(e)",
    "predetermined_changes": "2(f)", "validation_and_testing_procedures": "2(g)",
    "capabilities_and_limitations": "3", "performance_metrics_appropriateness": "4",
    "risk_management_system": "5", "lifecycle_changes": "6", "harmonised_standards": "7",
    "declaration_of_conformity": "8", "post_market_monitoring_plan": "9",
}


def _sha(obj: Any) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str).encode()).hexdigest()


def _safe(fn, default=None):
    try:
        return fn()
    except Exception as e:  # noqa: BLE001 - a section that cannot be read says so instead of failing the document
        return {"error": f"{type(e).__name__}: {e}"} if default is None else default


def instructions_for_use(store, ledger=None) -> dict:
    """Art. 13(3)(f): how to collect, store and interpret the logs this store produces."""
    receipts_on = bool(getattr(store, "receipts_enabled", False))
    # file NAMES, never paths: a path names a machine and a user, and this section is embedded in the
    # Annex IV skeleton, the deployer report and the Annex VIII export, which travel (red team, 2026-09-16)
    name = os.path.basename(str(getattr(store, "path", "") or ""))
    ledger_name = os.path.basename(str(getattr(ledger, "path", ""))) if ledger is not None else (name + ".actions.json" if name else None)
    return {
        "basis": "Art. 13(3)(f): the instructions for use contain the information needed to collect, store and "
                 "interpret the logs generated by the system.",
        "files": {
            "memory_store": name or None,
            "write_receipts": (name + ".receipts.json") if name else None,
            "erasure_tombstones": "kept inside the store file under the tombstone list; anchor() covers both chains",
            "action_ledger": ledger_name,
            "archives": "<ledger>.archive.NNNN.json beside the ledger, named by the checkpoint",
            "receipts_enabled": receipts_on,
            "note": "file names beside each other in one directory; the directory is the operator's",
        },
        "memory_receipt": {
            "one_per": "write (remember, decision, rectification); erasures append a tombstone",
            "fields": ["ts", "memory_id", "commit (hash of text, key and attribution)", "seq", "prev", "hash",
                       "sig and pubkey when a receipt key is set", "amends and amend_reason when a field was "
                       "legitimately rewritten"],
            "chain": "hash over the canonical entry; prev is the previous hash; genesis is 64 zeros",
        },
        "action_ledger_entry": {
            "one_per": "tool call, model call, oversight decision, disclosure, rights request, incident",
            "fields": ["v", "kind (action | oversight | disclosure | rights | incident)", "seq", "prev", "ts",
                       "started", "actor", "action", "status (ok | error)", "inputs_sha256", "output_sha256",
                       "memory_state {digest, records, last_receipt, receipts, recalled, recalled_at}",
                       "hash", "sig and pubkey when signed",
                       "kind-specific: event, reason, refers_to, decision_sha256 (oversight); session, channel, "
                       "disclosure_kind, shown_sha256, shown_chars (disclosure); event, subject, request_id, "
                       "manifest_sha256 or key and new_id (rights); title, severity, aware_ts, "
                       "report_deadline_ts, evidence (incident)"],
            "content": "inputs and outputs are stored as SHA-256 digests unless the ledger was opened with "
                       "keep_content=True; a redact callable can be applied before digesting",
        },
        "how_to_verify": [
            "inspeximus audit-build --out bundle.json && inspeximus audit-verify bundle.json    "
            "(memory chain, offline, no key needed; --expected-pubkey pins the signer)",
            "inspeximus actions verify <store>.actions.json    (action ledger, offline)",
            "inspeximus actions verify    (with the store present: also binds every entry's last_receipt to the "
            "memory chain, so a rewritten memory history fails from the action side)",
            "inspeximus actions knew SEQ    (the memory state at action SEQ and the provenance of what it recalled)",
            "inspeximus compliance --out report.html    (22 article-labelled controls with live counts)",
        ],
        "retention": {
            "memory": "inspeximus retention --apply erases records past a retention age (dry run by default) and "
                      "appends a tombstone for each; the receipt chain is never truncated",
            "action_ledger": "append-only. `inspeximus actions archive --keep-days N` moves entries older than N "
                             "days into <ledger>.archive.NNNN.json beside the ledger and starts the live file with "
                             "a signed checkpoint naming the archive, its SHA-256 and the archived tail; nothing "
                             "is deleted, the chain is unbroken, and the verifier follows the checkpoint into the "
                             "archive (a missing archive is reported, not skipped). `inspeximus actions attest "
                             "--policy-days N` appends a signed retention statement: oldest entry, counts, whether "
                             "the six-month floor has been observed",
            "archives": list((getattr(ledger, "archived", None) or {}).get("archive_chain", [])) if ledger is not None else [],
        },
        "interpretation": [
            "A memory_state.digest that differs between two actions means the store changed between them: a "
            "write, correction, revert or erasure.",
            "memory_state.recalled lists the record ids the last recall returned before the action; "
            "what_it_knew resolves them to their provenance and current status.",
            "An oversight entry's refers_to names the action a person decided about; an error action with no "
            "oversight after it is listed by oversight_report.",
            "An incident's report_deadline_ts is the Art. 73 clock from aware_ts; incident_report says whether "
            "it is overdue.",
        ],
    }


#: Annex VIII, the information submitted on registration (Art. 49). Section A: providers of high-risk
#: systems, Art. 49(1). Section B: providers relying on Art. 6(3), Art. 49(2), points 7 and 9 deleted by
#: Regulation (EU) 2026/1744. Section C: deployers that are public authorities or Union bodies, Art. 49(3).
#: Each field maps to its Annex VIII point; the value is the operator's unless the evidence can supply it.
REGISTRATION_FIELDS = {
    "A": {
        "provider_name_address_contact": "A.1", "submitter_on_behalf": "A.2", "authorised_representative": "A.3",
        "trade_name": "A.4", "intended_purpose_and_functions": "A.5", "information_used_and_operating_logic": "A.6",
        "status": "A.7", "notified_body_certificate": "A.8", "certificate_copy": "A.9", "member_states": "A.10",
        "eu_declaration_of_conformity": "A.11", "electronic_instructions_for_use": "A.12", "url": "A.13 (optional)",
    },
    "B": {
        "provider_name_address_contact": "B.1", "submitter_on_behalf": "B.2", "authorised_representative": "B.3",
        "trade_name": "B.4", "intended_purpose": "B.5", "art_6_3_conditions": "B.6", "status": "B.8",
    },
    "C": {
        "deployer_name_address_contact": "C.1", "submitter_on_behalf": "C.2", "provider_entry_url": "C.3",
        "fria_summary": "C.4", "dpia_summary": "C.5",
    },
}


def registration_export(store, ledger=None, operator: dict | None = None, section: str = "A",
                        expected_pubkey: str | None = None, now: float | None = None) -> dict:
    """The Annex VIII fields for registration in the EU database (Art. 49), as a JSON document: the
    operator's fields where only the provider or deployer can write them, and from the evidence the
    traceability reference (A.4, B.4), the description of the information the system uses (A.6), the
    electronic instructions for use (A.12) and, for a deployer, the FRIA and DPIA summaries (C.4, C.5)
    drawn from the deployer report. Not a submission: the EU database has its own form, and this is
    the content to paste into it, with every missing field named."""
    section = (section or "A").upper()
    if section not in REGISTRATION_FIELDS:
        raise ValueError("section must be A (provider, Art. 49(1)), B (Art. 6(3) provider, Art. 49(2)) or "
                         "C (deployer, Art. 49(3))")
    operator = dict(operator or {})
    fields = REGISTRATION_FIELDS[section]

    def op(field):
        v = operator.get(field)
        return v if v not in (None, "") else OPERATOR_INPUT

    anchor = _safe(lambda: store.anchor())
    tail = None
    if ledger is not None:
        ents = _safe(lambda: ledger.entries(), default=[])
        tail = ents[-1].get("hash") if isinstance(ents, list) and ents else None
    now = time.time() if now is None else now
    traceability = {
        "memory_layer": f"inspeximus {__version__}",
        "anchor_sth": anchor.get("sth_hash") if isinstance(anchor, dict) else None,
        "action_ledger_tail": tail,
        "note": "the anchor tree head and the ledger tail identify this store's history at export time; they "
                "change with every write, so they date the export rather than name the system. No file path: "
                "Art. 71(4) makes the database public and a path names a machine and a user",
    }
    out_fields: dict = {}
    for f, point in fields.items():
        out_fields[f] = {"annex_viii": point, "value": op(f)}
    if section in ("A", "B"):
        out_fields["trade_name"]["traceability_reference"] = traceability
    if section == "A":
        mem = _safe(lambda: store.memory_report())
        pii = _safe(lambda: store.pii_report())
        out_fields["information_used_and_operating_logic"]["evidence"] = {
            "memory_records": {k: mem.get(k) for k in ("total", "active", "superseded") if isinstance(mem, dict) and k in mem},
            "personal_data_types_tagged": sorted((pii.get("by_type") or {}).keys()) if isinstance(pii, dict) else None,
            "operating_logic_of_the_memory_layer": "deterministic keyed recall with supersession; no LLM on the "
                                                   "write path; every write, correction and erasure is a receipt",
        }
        out_fields["electronic_instructions_for_use"]["evidence"] = instructions_for_use(store, ledger)
    if section == "C":
        from .deployer import dpia_appendix, fria_appendix
        fria = fria_appendix(store, ledger, operator, expected_pubkey, now=now)
        dpia = dpia_appendix(store, ledger, operator, expected_pubkey, now=now)
        # C.4 is "a summary of the FINDINGS" of the FRIA: those are the deployer's, so the summary is the
        # operator's text and the evidence block lists only what the assessment rested on, as counts
        out_fields["fria_summary"]["evidence"] = {
            "oversight_recorded": {k: v for k, v in fria["27_1_e_human_oversight_implementation"]["evidence_recorded"].items()
                                   if k in ("oversight_events", "by_event", "distinct_actors", "actions",
                                            "actions_with_oversight", "stops", "recorded")},
            "incidents": {k: fria["27_1_f_measures_on_materialisation"]["evidence"]["incidents"].get(k)
                          for k in ("incidents", "not_yet_reported", "recorded")},
            "operator_fields_missing": fria["operator_fields_missing"],
            "note": "the findings are the deployer's (Annex VIII C.4); the observed period and frequency in "
                    "the deployer report are an input to the assessment, not a finding",
        }
        inv = dpia["35_7_a_description_of_processing"]["evidence_inventory_of_this_store"]
        meas = dpia["35_7_d_measures"]["evidence"]
        out_fields["dpia_summary"]["evidence"] = {
            "inventory": inv,
            "measures": {"integrity": {k: v for k, v in meas["integrity"].items() if k != "action_ledger_problems"},
                         "log_retention_status": meas["log_retention"].get("status"),
                         "data_subject_rights_exercised": meas["data_subject_rights_exercised"]},
            "operator_fields_missing": dpia["operator_fields_missing"],
        }
    doc = {
        "kind": "inspeximus.registration_export/1",
        "generated_at": time.time(),
        "inspeximus_version": __version__,
        "basis": "Regulation (EU) 2024/1689 Art. 49 and Annex VIII, Section " + section +
                 (" (points 7 and 9 deleted by Regulation (EU) 2026/1744)" if section == "B" else ""),
        "section": section,
        "fields": out_fields,
        "operator_fields_missing": [f for f in fields if operator.get(f) in (None, "")],
        "operator_fields_total": len(fields),
        "scope": "The content of a registration, not the registration: the EU database has its own form. "
                 "Fields marked OPERATOR INPUT REQUIRED are the provider's or deployer's own account.",
    }
    doc["content_sha256"] = _sha({k: v for k, v in doc.items() if k != "content_sha256"})
    return doc


def annex_iv(store, ledger=None, operator: dict | None = None, expected_pubkey: str | None = None) -> dict:
    """The Annex IV skeleton with the evidence sections filled from the store and ledger."""
    operator = dict(operator or {})
    from .compliance import compliance_report
    rep = _safe(lambda: compliance_report(store, expected_pubkey))
    mem = _safe(lambda: store.memory_report())
    pii = _safe(lambda: store.pii_report())
    gov = _safe(lambda: store.governance_report(expected_pubkey))
    anchor = _safe(lambda: store.anchor())
    oversight = _safe(lambda: ledger.oversight_report()) if ledger is not None else None
    ledger_ok = _safe(lambda: ledger.verify(expected_pubkey=expected_pubkey)) if ledger is not None else None

    def op(field):
        v = operator.get(field)
        return v if v not in (None, "") else OPERATOR_INPUT

    missing = [f for f in OPERATOR_FIELDS if operator.get(f) in (None, "")]

    doc = {
        "kind": "inspeximus.annex_iv_skeleton/1",
        "generated_at": time.time(),
        "inspeximus_version": __version__,
        "scope": "A skeleton: the evidence sections are filled from the live store and action ledger; every "
                 "field marked OPERATOR INPUT REQUIRED is the provider's own account and is not something a "
                 "memory library can write. Not a conformity assessment.",
        "sections": {
            "1_general_description": {
                "a_intended_purpose_provider_version": {"system_name": op("system_name"),
                                                        "intended_purpose": op("intended_purpose"),
                                                        "provider": op("provider"),
                                                        "system_version": op("system_version")},
                "b_interaction_with_other_systems": op("interaction_with_other_systems"),
                "c_software_versions": {"memory_layer": f"inspeximus {__version__}",
                                        "store_file": os.path.basename(str(getattr(store, "path", "") or "")),
                                        "other": op("software_and_firmware_versions")},
                "d_forms_placed_on_market": op("forms_placed_on_market"),
                "e_hardware": op("hardware_description"),
                "f_photographs_or_illustrations": op("photographs_or_illustrations"),
                "g_user_interface": op("user_interface"),
                "h_instructions_for_use_logs": instructions_for_use(store, ledger),
            },
            "2_elements_and_development": {
                "a_methods_and_third_party_tools": op("design_methods_and_third_party_tools"),
                "b_design_specifications": op("design_specifications_and_logic"),
                "c_system_architecture": op("system_architecture"),
                "d_data_requirements": {
                    "operator": op("training_data_and_datasheets"),
                    "memory_records": mem,
                    "personal_data_in_memory": pii,
                    "evidence_note": "Memory records are the runtime data the agent reads, not the training "
                                     "data; the counts above are what the store holds at generation time.",
                },
                "e_human_oversight_measures": {
                    "operator_measures": op("human_oversight_measures"),
                    "oversight_events_recorded": oversight,
                },
                "f_predetermined_changes": op("predetermined_changes"),
                "g_validation_and_testing": {
                    "operator_procedures": op("validation_and_testing_procedures"),
                    "memory_chain_verified": (gov.get("proof") or {}).get("verified") if isinstance(gov, dict) else None,
                    "action_ledger_verified": ledger_ok[0] if isinstance(ledger_ok, tuple) else None,
                    "action_ledger_problems": ledger_ok[1] if isinstance(ledger_ok, tuple) else None,
                },
                "h_cybersecurity_measures": {
                    "capability": {
                        "tamper_evidence": "hash-chained, optionally Ed25519-signed write receipts and action "
                                           "entries; anchor() signs a tree head; witness co-signing detects a split "
                                           "view; the action ledger binds each entry to the memory chain tail",
                        "poisoning_resistance": "keyed supersession with echo guard; influence gate withholds a "
                                                "single-sourced value from acting until corroborated",
                    },
                    "evidence": {"anchor": anchor},
                    "operator": op("cybersecurity_measures") if "cybersecurity_measures" in operator else None,
                },
            },
            "3_monitoring_functioning_control": {
                "capabilities_and_limitations": op("capabilities_and_limitations"),
                "controls_report": rep,
            },
            "4_performance_metrics": op("performance_metrics_appropriateness"),
            "5_risk_management_system": op("risk_management_system"),
            "6_lifecycle_changes": {"operator": op("lifecycle_changes"),
                                    "evidence": {"lifecycle_events": _safe(lambda: ledger.lifecycle_events(), default=[])
                                                 if ledger is not None else [],
                                                 "note": "the ledger's own lifecycle entries (configuration changes, "
                                                         "key rotations, substantial modifications, decommission), "
                                                         "each with an actor"},
                                    "capability": "every write, correction and erasure is a receipt; "
                                                  "history(key) lists a key's corrections"},
            "7_harmonised_standards": op("harmonised_standards"),
            "8_declaration_of_conformity": op("declaration_of_conformity"),
            "9_post_market_monitoring_plan": {"operator": op("post_market_monitoring_plan"),
                                              "capability": "oversight_report, incident_report and the "
                                                            "compliance report are periodic inputs to the plan"},
        },
        "operator_fields_missing": missing,
        "operator_fields_total": len(OPERATOR_FIELDS),
    }
    doc["content_sha256"] = _sha({k: v for k, v in doc.items() if k != "content_sha256"})
    return doc


def render_markdown(doc: dict, title: str = "Technical documentation skeleton (Annex IV)") -> str:
    """A readable rendering of the skeleton. Values that are dicts or lists are rendered as JSON blocks."""
    out = [f"# {title}", "",
           f"Generated {time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(doc.get('generated_at', 0)))} UTC by "
           f"inspeximus {doc.get('inspeximus_version')}. {doc.get('scope')}", "",
           f"Operator fields still to fill: {len(doc.get('operator_fields_missing', []))} of "
           f"{doc.get('operator_fields_total')}: {', '.join(doc.get('operator_fields_missing', [])) or 'none'}", ""]

    def title_of(key):
        head, _, rest = key.partition("_")
        rest = rest.replace("_", " ")
        if head.isdigit():
            return f"{head}. {rest[:1].upper()}{rest[1:]}"
        if len(head) == 1 and head.isalpha():
            return f"({head}) {rest[:1].upper()}{rest[1:]}"
        k = key.replace("_", " ")
        return k[:1].upper() + k[1:]

    def emit(key, val, level):
        out.append("#" * min(level, 6) + " " + title_of(key))
        out.append("")
        # recurse into the numbered sections and their lettered items; everything deeper is a block
        if isinstance(val, dict) and level <= 3 and "kind" not in val                 and any(isinstance(v, (dict, list)) for v in val.values()):
            for k, v in val.items():
                emit(k, v, level + 1)
            return
        if isinstance(val, (dict, list)):
            out.append("```json")
            out.append(json.dumps(val, indent=2, ensure_ascii=False, default=str))
            out.append("```")
        else:
            out.append(str(val))
        out.append("")

    for key, val in doc.get("sections", {}).items():
        emit(key, val, 2)
    out.append(f"Content hash: `{doc.get('content_sha256')}`")
    out.append("")
    return "\n".join(out)
