"""Write the obligation matrix into docs/EVIDENCE_PLATFORM_PLAN.md, from the code, on a fresh store.

The plan's hand-written status table was stale for four duties within two days of being written
(2026-09-15 to 2026-09-17: Art. 14, 50, 73 and GDPR 15 said "build" after they had shipped). A
table nobody regenerates is a table that lies, so this writes it between two markers and a test
(tests/test_the_coverage_table_is_current.py) fails when the plan and `inspeximus.coverage`
disagree, the way docs/CORE_MAP.md is kept current.

A FRESH store is used on purpose: the plan describes what the library can do, not what one store
holds, so every built duty reads CAPABILITY here and the two counts that matter are the covered
duties and the NOT COVERED ones.

    python tools/gen_coverage_table.py            # rewrite the block
    python tools/gen_coverage_table.py --check    # exit 1 if the block is stale
"""
from __future__ import annotations

import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
PLAN = os.path.join(ROOT, "docs", "EVIDENCE_PLATFORM_PLAN.md")
BEGIN = "<!-- coverage:begin (generated by tools/gen_coverage_table.py; do not edit by hand) -->"
END = "<!-- coverage:end -->"


def block() -> str:
    from inspeximus import Inspeximus
    from inspeximus.coverage import NOT_COVERED, coverage, render_markdown
    with tempfile.TemporaryDirectory() as d:
        rep = coverage(Inspeximus(os.path.join(d, "fresh.json"), receipts=True))
    gaps = [r for r in rep["rows"] if r["state"] == NOT_COVERED]
    head = (f"{rep['covered']} of {rep['in_scope']} in-scope duties covered by the library, "
            f"{len(gaps)} not covered, {rep['counts']['NOT APPLICABLE']} not applicable. "
            f"`inspeximus coverage` prints the same matrix for a real store, with EVIDENCE counts.")
    return "\n".join([BEGIN, "", head, "", render_markdown(rep), "", END])


def current() -> str:
    return open(PLAN, encoding="utf-8").read()


def rewrite(text: str, new_block: str) -> str:
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("plan has no coverage markers")
    return text[:i] + new_block + text[j + len(END):]


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    new = block()
    text = current()
    updated = rewrite(text, new)
    if "--check" in argv:
        if updated != text:
            print("STALE: docs/EVIDENCE_PLATFORM_PLAN.md coverage block differs from inspeximus.coverage; "
                  "run python tools/gen_coverage_table.py")
            return 1
        print("coverage block is current")
        return 0
    with open(PLAN, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print("wrote the coverage block into docs/EVIDENCE_PLATFORM_PLAN.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
