"""Generate install/index.html, the short URL https://dancenitra.github.io/inspeximus/install.

    python tools/gen_install_page.py           # write install/index.html
    python tools/gen_install_page.py --check   # exit 1 if the committed file is stale

The site is served with .nojekyll, so docs/install/index.md is published as raw Markdown and /install has
nothing to serve. This page carries the WHOLE Markdown, verbatim, in one <pre> block: an agent that fetches
/install gets every command without following a link, and there is one source of truth, because the page
is generated from the Markdown that CI executes (tools/run_install_page.py). A hand-kept copy would drift
from the commands that are tested.
"""
from __future__ import annotations

import html
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "install", "index.md")
OUT = os.path.join(ROOT, "install", "index.html")
RAW = "https://dancenitra.github.io/inspeximus/docs/install/index.md"
GITHUB = "https://github.com/DanceNitra/inspeximus/blob/main/docs/install/index.md"

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- GENERATED by tools/gen_install_page.py from docs/install/index.md. Do not edit by hand. -->
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'">
<link rel="icon" href="data:,">
<link rel="canonical" href="https://dancenitra.github.io/inspeximus/install/">
<link rel="alternate" type="text/markdown" href="{raw}">
<title>Install inspeximus</title>
<meta name="description" content="One memory for all your AI agents: the install steps an AI agent can follow for you.">
<style>
:root {{ --bg: #fbfbf9; --fg: #1b1d21; --muted: #5d636e; --line: #d9dce1; --accent: #2449a8; --code: #f1f2f4; }}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{ --bg: #14161a; --fg: #e7e9ed; --muted: #9aa1ad; --line: #30343c;
    --accent: #8fb0ff; --code: #23262c; }}
}}
:root[data-theme="dark"] {{ --bg: #14161a; --fg: #e7e9ed; --muted: #9aa1ad; --line: #30343c;
  --accent: #8fb0ff; --code: #23262c; }}
* {{ box-sizing: border-box; }}
body {{ margin: 0; background: var(--bg); color: var(--fg);
       font: 16px/1.55 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }}
main {{ max-width: 860px; margin: 0 auto; padding: 32px 16px 64px; }}
h1 {{ font-size: 1.6rem; line-height: 1.25; margin: 0 0 8px; }}
p {{ margin: 8px 0; }}
.lede {{ color: var(--muted); }}
a {{ color: var(--accent); }}
pre {{ background: var(--code); border: 1px solid var(--line); padding: 14px 16px; border-radius: 6px;
      margin-top: 24px; white-space: pre-wrap; overflow-wrap: anywhere;
      font: 0.85rem/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }}
</style>
</head>
<body>
<main>
<h1>Install inspeximus</h1>
<p class="lede">Give this page to your AI agent and ask it to install inspeximus: every AI agent on your computer
then shares one memory.</p>
<p>The same text as Markdown: <a href="{raw}">index.md</a>, or <a href="{github}">rendered on GitHub</a>.</p>
<pre id="install">{body}</pre>
</main>
</body>
</html>
"""


def render():
    md = open(SRC, encoding="utf-8").read().replace("\r\n", "\n")
    return TEMPLATE.format(raw=RAW, github=GITHUB, body=html.escape(md, quote=False))


def main(argv):
    page = render()
    if "--check" in argv:
        try:
            current = open(OUT, encoding="utf-8").read().replace("\r\n", "\n")
        except FileNotFoundError:
            current = None
        if current != page:
            print("install/index.html is stale: run python tools/gen_install_page.py")
            return 1
        print("install/index.html is current")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(page)
    print("wrote", os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
